"""initial

Revision ID: 0001
Revises:
Create Date: 2025-05-15 12:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "keywords",
        sa.Column("keyword", sa.String(length=500), nullable=False),
        sa.Column("search_volume_est", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("competition_score", sa.Float(), nullable=False, server_default="0.0"),
        sa.Column("avg_price", sa.Numeric(precision=10, scale=2), nullable=False, server_default="0"),
        sa.Column("listing_count", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("top_category", sa.String(length=255), nullable=True),
        sa.Column("related_tags", postgresql.JSONB(), nullable=False, server_default="[]"),
        sa.Column("trend_direction", sa.String(length=20), nullable=False, server_default="stable"),
        sa.Column("trend_data", postgresql.JSONB(), nullable=False, server_default="[]"),
        sa.Column("etsy_raw", postgresql.JSONB(), nullable=False, server_default="{}"),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.Column("last_updated", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("keyword"),
    )
    op.create_index(op.f("ix_keywords_keyword"), "keywords", ["keyword"], unique=False)

    op.create_table(
        "shops",
        sa.Column("shop_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=500), nullable=False),
        sa.Column("url", sa.String(length=1000), nullable=False),
        sa.Column("total_listings", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("total_reviews", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("avg_rating", sa.Numeric(precision=3, scale=2), nullable=False, server_default="0"),
        sa.Column("tags_used", postgresql.JSONB(), nullable=False, server_default="[]"),
        sa.Column("category_distribution", postgresql.JSONB(), nullable=False, server_default="[]"),
        sa.Column("price_range", postgresql.JSONB(), nullable=False, server_default="{}"),
        sa.Column("listing_frequency", postgresql.JSONB(), nullable=False, server_default="{}"),
        sa.Column("etsy_raw", postgresql.JSONB(), nullable=False, server_default="{}"),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.Column("last_updated", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("shop_id"),
    )
    op.create_index(op.f("ix_shops_shop_id"), "shops", ["shop_id"], unique=False)

    op.create_table(
        "listings",
        sa.Column("listing_id", sa.Integer(), nullable=False),
        sa.Column("shop_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("tags", postgresql.JSONB(), nullable=False, server_default="[]"),
        sa.Column("price", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("currency", sa.String(length=10), nullable=False, server_default="USD"),
        sa.Column("category", sa.String(length=500), nullable=True),
        sa.Column("category_path", postgresql.JSONB(), nullable=False, server_default="[]"),
        sa.Column("url", sa.String(length=1000), nullable=True),
        sa.Column("images", postgresql.JSONB(), nullable=False, server_default="[]"),
        sa.Column("favorites", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("review_count", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("rating", sa.Numeric(precision=3, scale=2), nullable=False, server_default="0"),
        sa.Column("views_est", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("etsy_raw", postgresql.JSONB(), nullable=False, server_default="{}"),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.Column("last_updated", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("listing_id"),
    )
    op.create_index(op.f("ix_listings_listing_id"), "listings", ["listing_id"], unique=False)
    op.create_index(op.f("ix_listings_shop_id"), "listings", ["shop_id"], unique=False)

    op.create_table(
        "ranking_snapshots",
        sa.Column("listing_id", sa.UUID(), nullable=False),
        sa.Column("keyword_id", sa.UUID(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("total_results", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("captured_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["keyword_id"], ["keywords.id"],),
        sa.ForeignKeyConstraint(["listing_id"], ["listings.id"],),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_ranking_snapshots_keyword_id"), "ranking_snapshots", ["keyword_id"], unique=False)
    op.create_index(op.f("ix_ranking_snapshots_listing_id"), "ranking_snapshots", ["listing_id"], unique=False)

    op.create_table(
        "seo_audits",
        sa.Column("listing_id", sa.UUID(), nullable=False),
        sa.Column("title_score", sa.Float(), nullable=False, server_default="0.0"),
        sa.Column("tag_score", sa.Float(), nullable=False, server_default="0.0"),
        sa.Column("description_score", sa.Float(), nullable=False, server_default="0.0"),
        sa.Column("overall_score", sa.Float(), nullable=False, server_default="0.0"),
        sa.Column("suggestions", postgresql.JSONB(), nullable=False, server_default="[]"),
        sa.Column("benchmarks", postgresql.JSONB(), nullable=False, server_default="{}"),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["listing_id"], ["listings.id"],),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_seo_audits_listing_id"), "seo_audits", ["listing_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_seo_audits_listing_id"), table_name="seo_audits")
    op.drop_table("seo_audits")
    op.drop_index(op.f("ix_ranking_snapshots_listing_id"), table_name="ranking_snapshots")
    op.drop_index(op.f("ix_ranking_snapshots_keyword_id"), table_name="ranking_snapshots")
    op.drop_table("ranking_snapshots")
    op.drop_index(op.f("ix_listings_shop_id"), table_name="listings")
    op.drop_index(op.f("ix_listings_listing_id"), table_name="listings")
    op.drop_table("listings")
    op.drop_index(op.f("ix_shops_shop_id"), table_name="shops")
    op.drop_table("shops")
    op.drop_index(op.f("ix_keywords_keyword"), table_name="keywords")
    op.drop_table("keywords")
    # ### end Alembic commands ###
